sopct = 0.207
bbpct = 0.133
hrpct = 0.006
babip = 0.266
pobip = 1 - babip
bippct = 1 - sopct - bbpct - hrpct
hippct = bippct * babip
outippct = bippct * pobip
outs = 450
totaloutpct = outippct + sopct
pctoutsfromip = outippct / totaloutpct
pctoutsfromso = sopct / totaloutpct
so = outs * pctoutsfromso
outsinplay = outs * pctoutsfromip
totalbip = outsinplay / pobip
hitsinplay = totalbip * babip
sotobbratio = bbpct / sopct
sotohrratio = hrpct / sopct
bb = so * sotobbratio
hr = so * sotohrratio
avg = (hitsinplay + hr) / (outs + hitsinplay + hr)
obp = (hitsinplay + hr + bb) / (outs + hitsinplay + hr + bb)
